user_name = "Mike"
plan_folder = "plans/"
slice_target = 300000
tokenizer_base = 25000
tokenizer_multiplier = 1.0
tokenizer_ratio = 4.0
penalty_size_threshold = 24000
penalty_size_exponent = 1.5
penalty_noise_bpl = 500
penalty_noise_factor = 2.0
penalty_cap = 10.0
edit_premium = 2.0
